// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年12月27日 下午3:54:47
// ======================================================


#import <Foundation/Foundation.h>

#pragma mark - 
@interface ReportList : NSObject
@property(nonatomic, strong) NSString *reportNo;  // ReportNo
@property(nonatomic, strong) NSString *reportID;  // ReportID
@property(nonatomic, strong) NSString *reportName;  // ReportName
@property(nonatomic, strong) NSString *sex;  // Sex
@property(nonatomic)         BOOL ifShow_M;  // IfShow_M
@property(nonatomic)         BOOL ifShow_F;  // IfShow_F
@property(nonatomic)         BOOL ifShow_C;  // IfShow_C
@property(nonatomic, strong) NSString *showOrder;  // ShowOrder
@end
