// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年12月27日 下午3:54:47
// ======================================================


#import "ReportList.h"
#import "ReportListManager.h"
#import <FMDB.h>

@implementation ReportListManager{
    FMDatabase  *_db;
}

static ReportListManager *_sReportListManager = nil;

#pragma mark -
+ (ReportListManager *) sharedManager
{
    @synchronized(self) {
        if (!_sReportListManager) {
            _sReportListManager = [[self alloc] init];
            [_sReportListManager initDataBase];
        }
    }
    return _sReportListManager;
}

-(void)initDataBase{

    // 文件路径
    
    NSString *filePath = [DocumentFile ProductPath:@"ReportList.sqlite"];
    // 实例化FMDataBase对象    
    _db = [FMDatabase databaseWithPath:filePath];
    
}

#pragma mark -
/**** 获取所有报告**/
- (NSMutableArray *)getAllReport{

    NSString *sqliteStr = @"SELECT * FROM reportList";
    return [self queryAllSqlite:sqliteStr];
}

/**** 获取所有男性报告**/
- (NSMutableArray *)getAllManReport{
    
    NSString *sqliteStr = @"SELECT * FROM reportList where ifShow_M = 1";
    return [self queryAllSqlite:sqliteStr];
}

/**** 获取所有女性报告**/
- (NSMutableArray *)getAllWomanReport{

    NSString *sqliteStr = @"SELECT * FROM reportList where ifShow_F = 1";
    return [self queryAllSqlite:sqliteStr];
}
/**** 获取所有儿童报告**/
- (NSMutableArray *)getAllChildrenReport{
    
    NSString *sqliteStr = @"SELECT * FROM reportList where ifShow_C = 1";
    return [self queryAllSqlite:sqliteStr];
}

- (NSMutableArray *)queryAllSqlite:(NSString *)sqliteStr {
    [_db open];
    
    NSMutableArray *dataArray = [[NSMutableArray alloc] init];
    
    FMResultSet *res = [_db executeQuery:sqliteStr];
    
    while ([res next]) {
        ReportList *report = [[ReportList alloc] init];
        report.reportNo = [res stringForColumn:@"reportNo"];
        report.reportID = [res stringForColumn:@"reportID"];
        report.reportName = [res stringForColumn:@"reportName"];
        report.sex = [res stringForColumn:@"sex"];
        report.ifShow_M = [res stringForColumn:@"ifShow_M"];
        report.ifShow_F = [res stringForColumn:@"ifShow_F"];
        report.ifShow_C = [res stringForColumn:@"ifShow_C"];
        report.showOrder = [res stringForColumn:@"showOrder"];
        [dataArray addObject:report];
    }
    
    [_db close];
    
    return dataArray;
}


@end
