// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年12月27日 下午3:54:47
// ======================================================


#import "ReportList.h"

#pragma mark - 
@implementation ReportList

@synthesize reportNo = _reportNo;
@synthesize reportID = _reportID;
@synthesize reportName = _reportName;
@synthesize sex = _sex;
@synthesize ifShow_M = _ifShow_M;
@synthesize ifShow_F = _ifShow_F;
@synthesize ifShow_C = _ifShow_C;
@synthesize showOrder = _showOrder;

- (NSString *)description
{
    NSLog(@"reportNo:%@", _reportNo);
    NSLog(@"reportID:%@", _reportID);
    NSLog(@"reportName:%@", _reportName);
    NSLog(@"sex:%@", _sex);
    NSLog(@"ifShow_M:%@", @(_ifShow_M));
    NSLog(@"ifShow_F:%@", @(_ifShow_F));
    NSLog(@"ifShow_C:%@", @(_ifShow_C));
    NSLog(@"showOrder:%@", _showOrder);
    
    return [super description];
}
@end
