// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年12月27日 下午3:55:35
// ======================================================


#import "TblMeasData.h"

#pragma mark - 
@implementation TblMeasData

@synthesize n_Age_Range_Low = _n_Age_Range_Low;
@synthesize n_Age_Range_High = _n_Age_Range_High;
@synthesize str_Weight_Type = _str_Weight_Type;
@synthesize str_Item_Sub_Name = _str_Item_Sub_Name;
@synthesize str_Item_Main_Name = _str_Item_Main_Name;
@synthesize str_Result = _str_Result;
@synthesize n_Item_Sub_ID = _n_Item_Sub_ID;
@synthesize n_Result = _n_Result;
@synthesize n_Item_Main_ID = _n_Item_Main_ID;
@synthesize n_Weight_Type = _n_Weight_Type;

- (NSString *)description
{
    NSLog(@"n_Age_Range_Low:%@", _n_Age_Range_Low);
    NSLog(@"n_Age_Range_High:%@", _n_Age_Range_High);
    NSLog(@"str_Weight_Type:%@", _str_Weight_Type);
    NSLog(@"str_Item_Sub_Name:%@", _str_Item_Sub_Name);
    NSLog(@"str_Item_Main_Name:%@", _str_Item_Main_Name);
    NSLog(@"str_Result:%@", _str_Result);
    NSLog(@"n_Item_Sub_ID:%@", _n_Item_Sub_ID);
    NSLog(@"n_Result:%@", _n_Result);
    NSLog(@"n_Item_Main_ID:%@", _n_Item_Main_ID);
    NSLog(@"n_Weight_Type:%@", _n_Weight_Type);

    return [super description];
}
@end