// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年12月27日 下午3:55:35
// ======================================================


#import <Foundation/Foundation.h>

#pragma mark - 
@interface TblMeasData : NSObject
@property(nonatomic, strong) NSString *n_Age_Range_Low;  // n_Age_Range_Low
@property(nonatomic, strong) NSString *n_Age_Range_High;  // n_Age_Range_High
@property(nonatomic, strong) NSString *str_Weight_Type;  // str_Weight_Type
@property(nonatomic, strong) NSString *str_Item_Sub_Name;  // str_Item_Sub_Name
@property(nonatomic, strong) NSString *str_Item_Main_Name;  // str_Item_Main_Name
@property(nonatomic, strong) NSString *str_Result;  // str_Result
@property(nonatomic, strong) NSString *n_Item_Sub_ID;  // n_Item_Sub_ID
@property(nonatomic, strong) NSString *n_Result;  // n_Result
@property(nonatomic, strong) NSString *n_Item_Main_ID;  // n_Item_Main_ID
@property(nonatomic, strong) NSString *n_Weight_Type;  // n_Weight_Type
@end
