// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年12月27日 下午3:56:37
// ======================================================


#import "TblSubItemCase.h"

#pragma mark - 
@implementation TblSubItemCase

@synthesize n_SubItemID = _n_SubItemID;
@synthesize n_NormaBegin = _n_NormaBegin;
@synthesize str_SubItemName = _str_SubItemName;
@synthesize db_SubItemVal0 = _db_SubItemVal0;
@synthesize db_SubItemVal1 = _db_SubItemVal1;
@synthesize db_SubItemVal2 = _db_SubItemVal2;
@synthesize db_SubItemVal3 = _db_SubItemVal3;
@synthesize str_NormalCall = _str_NormalCall;
@synthesize str_TensionCall = _str_TensionCall;
@synthesize str_SeriousCall = _str_SeriousCall;
@synthesize n_MainItemID = _n_MainItemID;
@synthesize str_MainItemName = _str_MainItemName;
@synthesize str_GentalCall = _str_GentalCall;
@synthesize str_Unit = _str_Unit;
@synthesize isShow = _isShow;
@synthesize seriousPoint = _seriousPoint;
@synthesize strDescription = _strDescription;

- (NSString *)description
{
    NSLog(@"n_SubItemID:%@", _n_SubItemID);
    NSLog(@"n_NormaBegin:%@", _n_NormaBegin);
    NSLog(@"str_SubItemName:%@", _str_SubItemName);
    NSLog(@"db_SubItemVal0:%@", _db_SubItemVal0);
    NSLog(@"db_SubItemVal1:%@", _db_SubItemVal1);
    NSLog(@"db_SubItemVal2:%@", _db_SubItemVal2);
    NSLog(@"db_SubItemVal3:%@", _db_SubItemVal3);
    NSLog(@"str_NormalCall:%@", _str_NormalCall);
    NSLog(@"str_TensionCall:%@", _str_TensionCall);
    NSLog(@"str_SeriousCall:%@", _str_SeriousCall);
    NSLog(@"n_MainItemID:%@", _n_MainItemID);
    NSLog(@"str_MainItemName:%@", _str_MainItemName);
    NSLog(@"str_GentalCall:%@", _str_GentalCall);
    NSLog(@"str_Unit:%@", _str_Unit);
    NSLog(@"isShow:%@", @(_isShow));
    NSLog(@"seriousPoint:%@", _seriousPoint);
    NSLog(@"strDescription:%@", _strDescription);

    return [super description];
}
@end
