// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年12月27日 下午3:56:37
// ======================================================


#import "TblSubItemCase.h"
#import "TblSubItemCaseManager.h"
#import <FMDB.h>
#pragma mark - 
#define AUTO_PLIST_TBLSUBITEMCASE_PATH   [[NSBundle mainBundle] pathForResource:@"TblSubItemCase" ofType:@"plist"]

#pragma mark - 
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_N_SUBITEMID      0   // n_SubItemID
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_N_NORMABEGIN      1   // n_NormaBegin
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_STR_SUBITEMNAME      2   // str_SubItemName
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_DB_SUBITEMVAL0      3   // db_SubItemVal0
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_DB_SUBITEMVAL1      4   // db_SubItemVal1
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_DB_SUBITEMVAL2      5   // db_SubItemVal2
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_DB_SUBITEMVAL3      6   // db_SubItemVal3
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_STR_NORMALCALL      7   // str_NormalCall
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_STR_TENSIONCALL      8   // str_TensionCall
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_STR_SERIOUSCALL      9   // str_SeriousCall
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_N_MAINITEMID      10   // n_MainItemID
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_STR_MAINITEMNAME      11   // str_MainItemName
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_STR_GENTALCALL      12   // str_GentalCall
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_STR_UNIT      13   // str_Unit
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_ISSHOW      14   // IsShow
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_SERIOUSPOINT      15   // SeriousPoint
#define AUTO_PLIST_TBLSUBITEMCASE_INDEX_STRDESCRIPTION      16   // strDescription

#pragma mark - 
@implementation TblSubItemCaseManager{
    FMDatabase  *_db;
}

static TblSubItemCaseManager *_sTblSubItemCaseManager = nil;

#pragma mark -
+ (TblSubItemCaseManager *) sharedManager
{
    @synchronized(self) {
        if (!_sTblSubItemCaseManager) {
            _sTblSubItemCaseManager = [[self alloc] init];
        }
    }
    return _sTblSubItemCaseManager;
}
- (id)init
{
    self = [super init];
    if (self) {
        // 文件路径
        NSString *filePath = [DocumentFile ProductPath:@"TblSubItemCase.sqlite"];
        // 实例化FMDataBase对象
        _db = [FMDatabase databaseWithPath:filePath];
    }
    return self;
}

#pragma mark -

/* 获取所有的条目*/
- (NSArray *)allTblSubItemCases {
    NSString *sqliteStr = @"SELECT * FROM TblSubItemCase";
    return [self queryAllSqlite:sqliteStr];
    
}

/* 获取对应报告的所有条目*/
- (NSArray *)getSingleReportAllSubItem:(NSString *)reportID {
    NSString *sqliteStr = [NSString stringWithFormat:@"SELECT * FROM TblSubItemCase where n_MainItemID = %@",reportID];
    return [self queryAllSqlite:sqliteStr];
}

- (NSMutableArray *)queryAllSqlite:(NSString *)sqliteStr {
    [_db open];
    
    NSMutableArray *dataArray = [[NSMutableArray alloc] init];
    
    FMResultSet *res = [_db executeQuery:sqliteStr];
    
    while ([res next]) {
        TblSubItemCase *report = [[TblSubItemCase alloc] init];
        report.n_SubItemID = [res stringForColumn:@"n_SubItemID"];
        report.n_NormaBegin = [res stringForColumn:@"n_NormaBegin"];
        report.str_SubItemName = [res stringForColumn:@"str_SubItemName"];
        report.db_SubItemVal0 = [res stringForColumn:@"db_SubItemVal0"];
        report.db_SubItemVal1 = [res stringForColumn:@"db_SubItemVal1"];
        report.db_SubItemVal2 = [res stringForColumn:@"db_SubItemVal2"];
        report.db_SubItemVal3 = [res stringForColumn:@"db_SubItemVal3"];
        report.str_NormalCall = [res stringForColumn:@"str_NormalCall"];
        report.str_TensionCall = [res stringForColumn:@"str_TensionCall"];
        report.str_SeriousCall = [res stringForColumn:@"str_SeriousCall"];
        report.n_MainItemID = [res stringForColumn:@"n_MainItemID"];
        report.str_MainItemName = [res stringForColumn:@"str_MainItemName"];
        report.str_GentalCall = [res stringForColumn:@"str_GentalCall"];
        report.str_Unit = [res stringForColumn:@"str_Unit"];
        report.isShow = [res stringForColumn:@"isShow"];
        report.seriousPoint = [res stringForColumn:@"seriousPoint"];
        report.strDescription = [res stringForColumn:@"strDescription"];
        [dataArray addObject:report];
    }
    
    [_db close];
    
    return dataArray;
}




@end
