// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年12月27日 下午3:56:37
// ======================================================


#import <Foundation/Foundation.h>

#pragma mark - 
@interface TblSubItemCase : NSObject
@property(nonatomic, strong) NSString *n_SubItemID;  // n_SubItemID
@property(nonatomic, strong) NSString *n_NormaBegin;  // n_NormaBegin
@property(nonatomic, strong) NSString *str_SubItemName;  // str_SubItemName
@property(nonatomic, strong) NSString *db_SubItemVal0;  // db_SubItemVal0
@property(nonatomic, strong) NSString *db_SubItemVal1;  // db_SubItemVal1
@property(nonatomic, strong) NSString *db_SubItemVal2;  // db_SubItemVal2
@property(nonatomic, strong) NSString *db_SubItemVal3;  // db_SubItemVal3
@property(nonatomic, strong) NSString *str_NormalCall;  // str_NormalCall
@property(nonatomic, strong) NSString *str_TensionCall;  // str_TensionCall
@property(nonatomic, strong) NSString *str_SeriousCall;  // str_SeriousCall
@property(nonatomic, strong) NSString *n_MainItemID;  // n_MainItemID
@property(nonatomic, strong) NSString *str_MainItemName;  // str_MainItemName
@property(nonatomic, strong) NSString *str_GentalCall;  // str_GentalCall
@property(nonatomic, strong) NSString *str_Unit;  // str_Unit
@property(nonatomic)         BOOL isShow;  // IsShow
@property(nonatomic, strong) NSString *seriousPoint;  // SeriousPoint
@property(nonatomic, strong) NSString *strDescription;  // strDescription
@end
