// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年12月27日 下午3:56:37
// ======================================================


#import <Foundation/Foundation.h>

#pragma mark - 
@class TblSubItemCase;
@interface TblSubItemCaseManager : NSObject
{
    NSMutableArray  *_tblSubItemCases;
}
+ (TblSubItemCaseManager *) sharedManager;
/* 获取所有数据*/
- (NSArray *)allTblSubItemCases;
/* 获取对应报告的所有条目*/
- (NSArray *)getSingleReportAllSubItem:(NSString *)reportID;

@end
