// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2017年1月3日 下午3:54:55
// ======================================================


#import "TblSuggest.h"

#pragma mark - 
@implementation TblSuggest

@synthesize reportNo = _reportNo;
@synthesize reportID = _reportID;
@synthesize type = _type;
@synthesize system = _system;
@synthesize suggest = _suggest;

- (NSString *)description
{
    NSLog(@"reportNo:%@", _reportNo);
    NSLog(@"reportID:%@", _reportID);
    NSLog(@"type:%@", _type);
    NSLog(@"system:%@", _system);
    NSLog(@"suggest:%@", _suggest);

    return [super description];
}
@end