// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2017年1月3日 下午3:54:55
// ======================================================


#import <Foundation/Foundation.h>

#pragma mark - 
@interface TblSuggest : NSObject
@property(nonatomic, strong) NSString *reportNo;  // ReportNo
@property(nonatomic, strong) NSString *reportID;  // ReportID
@property(nonatomic, strong) NSString *type;  // Type
@property(nonatomic, strong) NSString *system;  // System
@property(nonatomic, strong) NSString *suggest;  // Suggest
@end
